require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - bin/**/*
    - vendor/assets/**/*

Layout/EmptyLines:
  Exclude:
    - config/initializers/sorcery.rb

Layout/ExtraSpacing:
  Exclude:
    - db/migrate/**/*

Layout/IndentationConsistency:
  EnforcedStyle: rails
  Exclude:
    - config/routes.rb

Layout/SpaceBeforeFirstArg:
  Exclude:
    - config/routes.rb

Lint/Debugger:
  AutoCorrect: False

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb

Style/Documentation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/**/*

Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*
  Max: 20

Metrics/BlockLength:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - config/routes.rb

Metrics/LineLength:
  Max: 110
  Exclude:
    - Rakefile
    - Gemfile
    - config/**/*
    - lib/tasks/**/*
    - test/test_helper.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  ExcludedMethods:
    - base_attributes

Rails:
  Enabled: true
